version: '3.9'
services:
  backend-app:
    build:
      context: .
      dockerfile: local.Dockerfile
    command: '/app/scripts/docker/local-run.sh'
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - './src:/app/src'
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: main
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
      - './docker-config/mongo-init:/docker-entrypoint-initdb.d'

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'
      - './docker-config/redis-conf/redis.conf:/usr/local/etc/redis/redis.conf'

volumes:
  mongo-data:
  redis-data: